services:
  # Nginx reverse proxy for load balancing and SSL termination
  nginx:
    image: nginx:alpine
    container_name: mealsync-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      mealsync-app:
        condition: service_started  # Changed from service_healthy to service_started
    restart: unless-stopped
    networks:
      - mealsync-network

  mealsync-app:
    image: ${DOCKER_HUB_USERNAME}/mealsync-app:latest
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${RDS_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GOOGLE_APPLICATION_CREDENTIALS=/app/mealsync-451912-80d962e81ab0.json
      - JAVA_OPTS=-Xmx1g -Xms512m
    volumes:
      - ./env.properties:/app/env.properties:ro
      - ./mealsync-451912-80d962e81ab0.json:/app/mealsync-451912-80d962e81ab0.json:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 180s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    networks:
      - mealsync-network

networks:
  mealsync-network:
    driver: bridge